### ISSUE TITLE
When there is 3 right answers, they are marked incorrect

### ISSUE THREAD

**Issue by JasonEverling** [dthies/moodle-qbehaviour_deferredallnothing#5]
We started using your plugin and noticed if the question has 3 right answers then they are marked as incorrect still even though they selected all 3 right answers. I see a pull request https://github.com/dthies/moodle-qbehaviour_deferredallnothing/pull/3 related to this it looks like. I have forked this repo and will apply the propsoed changes to see if it helps.

Jason

**Comment by JasonEverling** [comment]
An update, I made a comment on the PR but in case you missed it, 
the issue arises when you create a multiple choice question, they select the 3 right answers and THEN also select an additional wrong answer they still get it right. The only way to prevent that from happening is to set the wrong answers with a negative score instead of leaving them at 'none'

**Comment by JasonEverling** [comment]
@dthies Did you get a chance to check on this? I finally was able to reproduce as noted in previous comment.

**Comment by dthies** [comment]
@JasonEverling From what I can see from you comments, it really is acting as I would expect the multichoice question to behave. As long as the score adds to 100% the answer is marked correct and should receive the full marks. In order to prevent this, you have to set the negative marks. This is confusing, but is a feature of the question type, not this behavior.
